- hosts: agent
  tasks:
    - name: NTP OS Package Installation
      package: name=ntp state=present
    - name: NTP File Configurations
      copy: src=/root/ansible/testfile dest=/tmp
      notify:
      - restart ntp
      ignore_errors: yes
    - name: To start NTP services
      service: name=ntpd state=started enabled=yes
  handlers:
    - name: restart ntp
      service: name=ntpd state=restarted

