---
- name: Apache webserver deployment
  hosts: agent
  tasks:
    - name: Installing Apache packages
      yum: name=httpd state=present
    - name: Changing Listening port to 81
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: Listen 80
        line: Listen 81
    - name: Configuring Apache configuration files
      copy: dest=/var/www/html/index.html content="<h1>This is a demo for Apache Webserver!</h1>"
    - name: Starting Apache webservice
      service: name=httpd enabled=yes state=started
